server:
  port: 8080

wallet-service:
  url: "http://wallet-service:9090"

spring:
  application:
    name: gateway
  main:
    banner-mode: off

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      spring.json.trusted.packages: "*"

  data:
    redis:
      host: redis
      port: 6379
      reactive:
        timeout: 2s
      repositories: false